<div class="simpleContact">
	<p><?php echo __('Danke, das Sie unser Kontaktformular verwendet haben. Wir werden Ihre Anfrage in den n&auml;chsten Tagen bearbeiten und Ihnen ggfs. eine Antwort zukommen lassen.', 'simplecontact'); ?></p>
	<div style="font-size:10px; float:right; padding:25px;"><a href="http://simplecontact.united20.de/" title="<?php echo __('Kontaktformular für Wordpress'); ?>" style="font-size:10px;">Kontaktformular</a> by united20.de</div>
</div>