<div class="simpleContact">
	<form id="sc-form" action="" method="post">
		<table class="sc-form-table">
			<tr>
				<td class="sc-col-title">
					<label for="sc-username"><?php echo __('Benutzername', 'simplecontact'); ?></label>
				</td>
				<td class="sc-col-value">
					<?php if (!empty($request['username'])) : ?>
						<div id="sc-username"><?php echo $request['username']; ?> <input type="hidden" name="simple_contact[username]" value="<?php echo $request['username']; ?>" /></div>
					<?php else : ?>
						<input type="text" name="simple_contact[username]" id="sc-username" value="<?php echo (isset($this->form['username']) ? $this->form['username'] : ''); ?>" />
					<?php endif; ?>
					<?php if ($this->hasError('error username')) : ?><div class="sc-form-error"><?php echo __('Bitte geben Sie ihren Benutzernamen ein.', 'simplecontact'); ?></div><?php endif; ?>
				</td>
			</tr>
			<tr>
				<td class="sc-col-title">
					<label for="sc-email"><?php echo __('E-Mail Adresse', 'simplecontact'); ?></label>
				</td>
				<td class="sc-col-value">
					<?php if (!empty($request['email'])) : ?>
						<div id="sc-email"><?php echo $request['email']; ?> <input type="hidden" name="simple_contact[email]" value="<?php echo $request['email']; ?>" /></div>
					<?php else : ?>
						<input type="text" name="simple_contact[email]" id="sc-email" value="<?php echo (isset($this->form['email']) ? $this->form['email'] : ''); ?>" />
					<?php endif; ?>
					<?php if ($this->hasError('error email')) : ?><div class="sc-form-error"><?php echo __('Bitte geben Sie eine g&uuml;ltige E-Mail Adresse ein.', 'simplecontact'); ?></div><?php endif; ?>
				</td>
			</tr>
			<tr>
				<td class="sc-col-title">
					<label for="sc-subject"><?php echo __('Betreff', 'simplecontact'); ?></label>
				</td>
				<td class="sc-col-value">
					<?php if (!empty($request['subject']) && isset($subjects[$request['subject']])) : ?>
						<div id="sc-subject"><?php echo $subjects[$request['subject']]; ?> <input type="hidden" name="simple_contact[subject]" value="<?php echo $request['subject']; ?>" /></div>
					<?php else : ?>
						<select name="simple_contact[subject]" id="sc-subject">
							<option value="0"><?php echo __('--- Bitte w&auml;hlen ---', 'simplecontact'); ?></option>
							<?php foreach ($subjects as $key => $value) : ?>
								<option value="<?php echo $key; ?>"<?php if ($this->form['subject'] == $key): ?> selected="selected"<?php endif; ?>><?php echo $value; ?></option>
							<?php endforeach; ?>
						</select>
					<?php endif; ?>
					<?php if ($this->hasError('error subject')) : ?><div class="sc-form-error"><?php echo __('Bitte w&auml;hlen Sie einen Betreff aus.', 'simplecontact'); ?></div><?php endif; ?>
				</td>
			</tr>
			<tr>
				<td class="sc-col-title">
					<label for="sc-message"><?php echo __('Nachricht', 'simplecontact'); ?></label>
				</td>
				<td class="sc-col-value">
					<textarea name="simple_contact[message]" id="sc-message" rows="5" cols="25"><?php if (isset($this->form['message'])) : ?><?php echo $this->form['message']; ?><?php endif; ?></textarea>
					<?php if ($this->hasError('error message')) : ?><div class="sc-form-error"><?php echo __('Bitte geben Sie eine Nachricht ein.', 'simplecontact'); ?><?php endif; ?> <?php if ($this->config['message_min_length']) : ?><?php sprintf(__('(mindestens %s Zeichen)', 'simplecontact'), $this->config['message_min_length']); ?></div><?php endif; ?>
				</td>
			</tr>
			<?php if ($this->config['captcha']) : ?>
				<tr>
					<td class="sc-col-title">
						<label for="sc-code"><?php echo __('Code eingeben', 'simplecontact'); ?></label>
					</td>
					<td class="sc-col-value">
						<script src="<?php echo $path; ?>js/captcha.js" type="text/javascript"></script>
						<img src="<?php echo $path; ?>captcha.php?code=<?php echo $captchaId; ?>" id="sc-captcha" onclick="reloadCaptcha('sc-captcha', 'sc-captcha-id', '<?php echo $path; ?>captcha.php'); return false;" alt="Code eingeben" width="120" height="40" /><br />
						<input type="hidden" name="simple_contact[captcha_id]" id="sc-captcha-id" value="<?php echo $captchaId; ?>" />
						<input type="text" name="simple_contact[code]" id="sc-code" value="" />
						<?php if ($this->hasError('error captcha')) : ?><div class="sc-form-error"><?php echo __('Bitte geben Sie den korrekten graphischen Code ein.', 'simplecontact'); ?></div><?php endif; ?>
					</td>
				</tr>
			<?php endif; ?>
			<tr>
				<td class="sc-col-title">&nbsp;</td>
				<td class="sc-col-value">
					<input type="submit" name="simple_contact[submit]" value=" <?php echo __('Nachricht absenden', 'simplecontact'); ?> " />
				</td>
			</tr>
		</table>
		<div style="font-size:10px; float:right; padding:25px;"><a href="http://simplecontact.united20.de/" title="<?php echo __('Kontaktformular für Wordpress'); ?>" style="font-size:10px;">Kontaktformular</a> by united20.de</div>
	</form>
</div>